version: "3.9"
services:
  web:
    build: .
    command: gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static
    env_file:
      - .env
