services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      - name: db
        mountPath: /var/lib/db
